<?xml version="1.0"?>
<!DOCTYPE project>

<project name="document-library-sync-hook" basedir="." default="deploy">
	<property name="ant.build.javac.source" value="1.8" />
	<property name="ant.build.javac.target" value="1.8" />
	<property name="javac.compiler" value="modern" />
	<import file="../build-common-hook.xml" />
</project>
